const EmojiList = [
  // Default
  {
    names: ['Smile'],
    imgUrl: '/images/emoji/smile.png',
    id: ':smile:',
    category: 'DEFAULT',
  },
  {
    names: ['Big Smile'],
    imgUrl: '/images/emoji/big_smile.png',
    id: ':bigsmile:',
    category: 'DEFAULT',
  },
  {
    names: ['Sweat Smile'],
    imgUrl: '/images/emoji/sweat_smile.png',
    id: ':sweatsmile:',
    category: 'DEFAULT',
  },
  {
    names: ['ROFL'],
    imgUrl: '/images/emoji/rofl.png',
    id: ':rofl:',
    category: 'DEFAULT',
  },
  {
    names: ['Wink'],
    imgUrl: '/images/emoji/wink.png',
    id: ':wink:',
    category: 'DEFAULT',
  },
  {
    names: ['Wink With Tongue'],
    imgUrl: '/images/emoji/winking_tongue.png',
    id: ':winkt:',
    category: 'DEFAULT',
  },
  {
    names: ['Closed With Tongue'],
    imgUrl: '/images/emoji/stuck_out_closed.png',
    id: ':cwt:',
    category: 'DEFAULT',
  },
  {
    names: ['Frowning'],
    imgUrl: '/images/emoji/frowning.png',
    id: ':frowning:',
    category: 'DEFAULT',
  },
  {
    names: ['Weary'],
    imgUrl: '/images/emoji/weary.png',
    id: ':weary:',
    category: 'DEFAULT',
  },
  {
    names: ['Angry'],
    imgUrl: '/images/emoji/angry.png',
    id: ':angry:',
    category: 'DEFAULT',
  },
  {
    names: ['Sunglasses'],
    imgUrl: '/images/emoji/sunglasses.png',
    id: ':sunglasses:',
    category: 'DEFAULT',
  },
  {
    names: ['Heart Eyes'],
    imgUrl: '/images/emoji/heart_eyes.png',
    id: ':heyes:',
    category: 'DEFAULT',
  },
  {
    names: ['Money'],
    imgUrl: '/images/emoji/money_mouth.png',
    id: ':mm:',
    category: 'DEFAULT',
  },
  {
    names: ['Hot Face'],
    imgUrl: '/images/emoji/hot_face.png',
    id: ':hf:',
    category: 'DEFAULT',
  },
  {
    names: ['Cold Face'],
    imgUrl: '/images/emoji/cold_face.png',
    id: ':cf:',
    category: 'DEFAULT',
  },
  {
    names: ['Heart'],
    imgUrl: '/images/emoji/default_heart.png',
    id: ':heart:',
    category: 'DEFAULT',
  },
  {
    names: ['Pooh'],
    imgUrl: '/images/emoji/poop.png',
    id: ':pooh:',
    category: 'DEFAULT',
  },
  {
    names: ['Alien'],
    imgUrl: '/images/emoji/alien.png',
    id: ':alien:',
    category: 'DEFAULT',
  },
  {
    names: ['Rocket'],
    imgUrl: '/images/emoji/rocket.png',
    id: ':rocket:',
    category: 'DEFAULT',
  },
  {
    names: ['Skull Cross Bones'],
    imgUrl: '/images/emoji/skull_crossbones.png',
    id: ':scb:',
    category: 'DEFAULT',
  },
  {
    names: ['Beers'],
    imgUrl: '/images/emoji/beers.png',
    id: ':beers:',
    category: 'DEFAULT',
  },
  {
    names: ['Ghost'],
    imgUrl: '/images/emoji/ghost.png',
    id: ':ghost:',
    category: 'DEFAULT',
  },
  {
    // Pepe
    names: ['Pepe'],
    imgUrl: '/images/emoji/pepe.png',
    id: ':pepe:',
    category: 'PEPE',
  },
  {
    names: ['Batman Pepe'],
    imgUrl: '/images/emoji/bat_pepe.png',
    id: ':batman_pepe:',
    category: 'PEPE',
  },
  {
    names: ['Lunatic Pepe'],
    imgUrl: '/images/emoji/pepe_2.png',
    id: ':lunatic_pepe:',
    category: 'PEPE',
  },
  {
    names: ['Sad Pepe'],
    imgUrl: '/images/emoji/pepe_sad.gif',
    id: ':pepe_sad:',
    category: 'PEPE',
  },
  {
    names: ['Pepe Heart'],
    imgUrl: '/images/emoji/pepe_7.png',
    id: ':pepe_heart:',
    category: 'PEPE',
  },
  {
    names: ['Suspicious Pepe'],
    imgUrl: '/images/emoji/pepe_8.png',
    id: ':suspicious_pepe:',
    category: 'PEPE',
  },
  {
    names: ['Cheering Pepe'],
    imgUrl: '/images/emoji/pepe_10.png',
    id: ':cheering_pepe:',
    category: 'PEPE',
  },
  {
    names: ['Thug Pepe'],
    imgUrl: '/images/emoji/pepe_11.png',
    id: ':thug_pepe:',
    category: 'PEPE',
  },
  {
    names: ['Pepe Wink'],
    imgUrl: '/images/emoji/pepe_wink.png',
    id: ':pepe_wink:',
    category: 'PEPE',
  },
  {
    names: ['Smoking Pepe'],
    imgUrl: '/images/emoji/pepe_smoke.gif',
    id: ':smoking_pepe:',
    category: 'PEPE',
  },
  {
    names: ['Pepe Loves You'],
    imgUrl: '/images/emoji/pepe_love.gif',
    id: ':pepe_loves_you:',
    category: 'PEPE',
  },
  {
    names: ['Excited Pepe'],
    imgUrl: '/images/emoji/pepe_excited.gif',
    id: ':excited_pepe:',
    category: 'PEPE',
  },
  {
    names: ['Magnify Pepe'],
    imgUrl: '/images/emoji/pepe_magnify.gif',
    id: ':magnify_pepe:',
    category: 'PEPE',
  },
  {
    names: ['Shooting Pepe'],
    imgUrl: '/images/emoji/pepe_shoot.gif',
    id: ':shooting_pepe:',
    category: 'PEPE',
  },
  {
    names: ['Pepe Mods'],
    imgUrl: '/images/emoji/pepe_mods.gif',
    id: ':pepe_mods:',
    category: 'PEPE',
  },
  {
    names: ['Trippin Pepe'],
    imgUrl: '/images/emoji/pepe_log.gif',
    id: ':trippin_pepe:',
    category: 'PEPE',
  },
  {
    names: ['Skill Issue Pepe'],
    imgUrl: '/images/emoji/pepe_skill_issue.gif',
    id: ':skill_issue_pepe:',
    category: 'PEPE',
  },
  {
    names: ['Ban Pepe'],
    imgUrl: '/images/emoji/pepe_ban.gif',
    id: ':ban_pepe:',
    category: 'PEPE',
  },
  {
    names: ['Nervous Pepe'],
    imgUrl: '/images/emoji/pepe_nervous.gif',
    id: ':nervous_pepe:',
    category: 'PEPE',
  },
  {
    names: ['Weird Pepe'],
    imgUrl: '/images/emoji/pepe_weird.gif',
    id: ':weird_pepe:',
    category: 'PEPE',
  },
  {
    names: ['Driving Pepe'],
    imgUrl: '/images/emoji/pepe_driver.gif',
    id: ':driving_pepe: ',
    category: 'PEPE',
  },
  {
    names: ['Ghostface Pepe'],
    imgUrl: '/images/emoji/pepe_ghostface.png',
    id: ':ghostface_pepe:',
    category: 'PEPE',
  },
  {
    names: ['Flexing Pepe'],
    imgUrl: '/images/emoji/pepe_flex.gif',
    id: ':flexing_pepe:',
    category: 'PEPE',
  },
  {
    names: ['Popcorn Pepe'],
    imgUrl: '/images/emoji/popcorn_pepe.gif',
    id: ':popcorn:',
    category: 'PEPE',
  },
  // Kek
  {
    names: ['El Risitas Kek'],
    imgUrl: '/images/emoji/kek_laugh.gif',
    id: ':kekl:',
    category: 'OTHER',
  },
  {
    names: ['Wojak'],
    imgUrl: '/images/emoji/wojak_3.png',
    id: ':wojak:',
    category: 'OTHER',
  },
  {
    names: ['Smile'],
    imgUrl: '/images/emoji/lmao.png',
    id: ':smile',
    category: 'OTHER',
  },
  {
    names: ['Chad'],
    imgUrl: '/images/emoji/chad.png',
    id: ':chad:',
    category: 'OTHER',
  },
  {
    names: ['Wojak Pepe Hoodie'],
    imgUrl: '/images/emoji/wojak_pepe_hoodie.png',
    id: ':wojak_pepe_hoodie:',
    category: 'OTHER',
  },
  {
    names: ['Kek'],
    imgUrl: '/images/emoji/kek_2.png',
    id: ':kekwait:',
    category: 'OTHER',
  },
  {
    names: ['Up Force'],
    imgUrl: '/images/emoji/upforce.gif',
    id: ':upforce:',
    category: 'OTHER',
  },
  {
    names: ['Brimson Kek'],
    imgUrl: '/images/emoji/brimson_kek.png',
    id: ':brimson:',
    category: 'OTHER',
  },
  // Family guy
  {
    names: ['Just Peter'],
    imgUrl: '/images/emoji/just_peter.png',
    id: ':just_peter:',
    category: 'OTHER',
  },
  {
    names: ['Disco Cat'],
    imgUrl: '/images/emoji/disco_cat.gif',
    id: ':disco_cat:',
    category: 'OTHER',
  },
  {
    names: ['Drinking Peter'],
    imgUrl: '/images/emoji/peter_drink.png',
    id: ':drinking_peter:',
    category: 'OTHER',
  },
  // Wojak
  {
    names: ['Wojak & Pepe'],
    imgUrl: '/images/emoji/wojak_1.png',
    id: ':wojak_and_pepe:',
    category: 'OTHER',
  },
  {
    names: ['Sunglasses Wojak'],
    imgUrl: '/images/emoji/wojak_2.png',
    id: ':sunglasses_wojak:',
    category: 'OTHER',
  },
  {
    names: ['Just Wojak'],
    imgUrl: '/images/emoji/wojak_4.png',
    id: ':just_wojak:',
    category: 'OTHER',
  },
  {
    names: ['Watching Tom'],
    imgUrl: '/images/emoji/watching_tom.png',
    id: ':watching_tom:',
    category: 'OTHER',
  },
  {
    names: ['Trippin Wojak'],
    imgUrl: '/images/emoji/trippin_wojak.png',
    id: ':trippin_wojak:',
    category: 'OTHER',
  },
  {
    names: ['Pikachu'],
    imgUrl: '/images/emoji/pikachu.png',
    id: ':pika:',
    category: 'OTHER',
  },
  {
    names: ['Niceee'],
    imgUrl: '/images/emoji/sp_nice.png',
    id: ':niceee:',
    category: 'OTHER',
  },
  {
    names: ['Kazama'],
    imgUrl: '/images/emoji/kazama.png',
    id: ':kazama:',
    category: 'OTHER',
  },
  {
    names: ['Bitcoin'],
    imgUrl: '/images/emoji/bitcoin.png',
    id: ':bitcoin:',
    category: 'OTHER',
  },
  {
    names: ['Kazama Gif'],
    imgUrl: '/images/emoji/kazama_gif.gif',
    id: ':kazama_gif:',
    category: 'OTHER',
  },
  {
    names: ['Spinning Dollar'],
    imgUrl: '/images/emoji/spinning_dollar.gif',
    id: ':spinning_dollar:',
    category: 'OTHER',
  },
  {
    names: ['Bouncing Eyes'],
    imgUrl: '/images/emoji/bouncing_eyes.gif',
    id: ':bouncing_eyes:',
    category: 'OTHER',
  },
  {
    names: ['Sparrow Gasp'],
    imgUrl: '/images/emoji/sparrow_gasp.gif',
    id: ':sparrow_gasp:',
    category: 'OTHER',
  },
  {
    names: ['Aw Yeah'],
    imgUrl: '/images/emoji/aw_yeah.gif',
    id: ':aw_yeah:',
    category: 'OTHER',
  },
]

export default EmojiList
