import React, { createContext, useContext, useState, useEffect } from 'react'
import axios from 'axios'
import { useWeb3React } from '@kazama-defi/wagmi'
import { getLotteryData } from 'utils/apiRoutes'
import { useSocket } from './SocketManager'

// Create a new context with initial state as defaultValue
const LotteryDataContext = createContext({
  draw_active: false,
  settings: {
    enabled: true,
    stake_fee: 0.7,
    min_stakers: 10,
    winning_spots: 50,
    draw_timespan: 36000000,
  },
  lottery_data: {
    current_id: 0,
    total_kazama_burned: 0,
    current_pot: 0,
    next_draw: new Date(Date.now() + 3 * 60 * 60 * 1000),
    next_round_stakers: [],
    winners: {
      1: { username: '', avatar: '', amount: 0, rank: 0 },
      2: { username: '', avatar: '', amount: 0, rank: 0 },
      3: { username: '', avatar: '', amount: 0, rank: 0 },
      4: { username: '', avatar: '', amount: 0, rank: 0 },
      5: { username: '', avatar: '', amount: 0, rank: 0 },
      6: { username: '', avatar: '', amount: 0, rank: 0 },
      7: { username: '', avatar: '', amount: 0, rank: 0 },
      8: { username: '', avatar: '', amount: 0, rank: 0 },
      9: { username: '', avatar: '', amount: 0, rank: 0 },
      10: { username: '', avatar: '', amount: 0, rank: 0 },
      11: { username: '', avatar: '', amount: 0, rank: 0 },
      12: { username: '', avatar: '', amount: 0, rank: 0 },
      13: { username: '', avatar: '', amount: 0, rank: 0 },
      14: { username: '', avatar: '', amount: 0, rank: 0 },
      15: { username: '', avatar: '', amount: 0, rank: 0 },
      16: { username: '', avatar: '', amount: 0, rank: 0 },
      17: { username: '', avatar: '', amount: 0, rank: 0 },
      18: { username: '', avatar: '', amount: 0, rank: 0 },
      19: { username: '', avatar: '', amount: 0, rank: 0 },
      20: { username: '', avatar: '', amount: 0, rank: 0 },
      21: { username: '', avatar: '', amount: 0, rank: 0 },
      22: { username: '', avatar: '', amount: 0, rank: 0 },
      23: { username: '', avatar: '', amount: 0, rank: 0 },
      24: { username: '', avatar: '', amount: 0, rank: 0 },
      25: { username: '', avatar: '', amount: 0, rank: 0 },
      26: { username: '', avatar: '', amount: 0, rank: 0 },
      27: { username: '', avatar: '', amount: 0, rank: 0 },
      28: { username: '', avatar: '', amount: 0, rank: 0 },
      29: { username: '', avatar: '', amount: 0, rank: 0 },
      30: { username: '', avatar: '', amount: 0, rank: 0 },
      31: { username: '', avatar: '', amount: 0, rank: 0 },
      32: { username: '', avatar: '', amount: 0, rank: 0 },
      33: { username: '', avatar: '', amount: 0, rank: 0 },
      34: { username: '', avatar: '', amount: 0, rank: 0 },
      35: { username: '', avatar: '', amount: 0, rank: 0 },
      36: { username: '', avatar: '', amount: 0, rank: 0 },
      37: { username: '', avatar: '', amount: 0, rank: 0 },
      38: { username: '', avatar: '', amount: 0, rank: 0 },
      39: { username: '', avatar: '', amount: 0, rank: 0 },
      40: { username: '', avatar: '', amount: 0, rank: 0 },
      41: { username: '', avatar: '', amount: 0, rank: 0 },
      42: { username: '', avatar: '', amount: 0, rank: 0 },
      43: { username: '', avatar: '', amount: 0, rank: 0 },
      44: { username: '', avatar: '', amount: 0, rank: 0 },
      45: { username: '', avatar: '', amount: 0, rank: 0 },
      46: { username: '', avatar: '', amount: 0, rank: 0 },
      47: { username: '', avatar: '', amount: 0, rank: 0 },
      48: { username: '', avatar: '', amount: 0, rank: 0 },
      49: { username: '', avatar: '', amount: 0, rank: 0 },
      50: { username: '', avatar: '', amount: 0, rank: 0 },
    },
    previous_winners: {
      1: { username: '', avatar: '', amount: 0, rank: 0 },
      2: { username: '', avatar: '', amount: 0, rank: 0 },
      3: { username: '', avatar: '', amount: 0, rank: 0 },
      4: { username: '', avatar: '', amount: 0, rank: 0 },
      5: { username: '', avatar: '', amount: 0, rank: 0 },
      6: { username: '', avatar: '', amount: 0, rank: 0 },
      7: { username: '', avatar: '', amount: 0, rank: 0 },
      8: { username: '', avatar: '', amount: 0, rank: 0 },
      9: { username: '', avatar: '', amount: 0, rank: 0 },
      10: { username: '', avatar: '', amount: 0, rank: 0 },
      11: { username: '', avatar: '', amount: 0, rank: 0 },
      12: { username: '', avatar: '', amount: 0, rank: 0 },
      13: { username: '', avatar: '', amount: 0, rank: 0 },
      14: { username: '', avatar: '', amount: 0, rank: 0 },
      15: { username: '', avatar: '', amount: 0, rank: 0 },
      16: { username: '', avatar: '', amount: 0, rank: 0 },
      17: { username: '', avatar: '', amount: 0, rank: 0 },
      18: { username: '', avatar: '', amount: 0, rank: 0 },
      19: { username: '', avatar: '', amount: 0, rank: 0 },
      20: { username: '', avatar: '', amount: 0, rank: 0 },
      21: { username: '', avatar: '', amount: 0, rank: 0 },
      22: { username: '', avatar: '', amount: 0, rank: 0 },
      23: { username: '', avatar: '', amount: 0, rank: 0 },
      24: { username: '', avatar: '', amount: 0, rank: 0 },
      25: { username: '', avatar: '', amount: 0, rank: 0 },
      26: { username: '', avatar: '', amount: 0, rank: 0 },
      27: { username: '', avatar: '', amount: 0, rank: 0 },
      28: { username: '', avatar: '', amount: 0, rank: 0 },
      29: { username: '', avatar: '', amount: 0, rank: 0 },
      30: { username: '', avatar: '', amount: 0, rank: 0 },
      31: { username: '', avatar: '', amount: 0, rank: 0 },
      32: { username: '', avatar: '', amount: 0, rank: 0 },
      33: { username: '', avatar: '', amount: 0, rank: 0 },
      34: { username: '', avatar: '', amount: 0, rank: 0 },
      35: { username: '', avatar: '', amount: 0, rank: 0 },
      36: { username: '', avatar: '', amount: 0, rank: 0 },
      37: { username: '', avatar: '', amount: 0, rank: 0 },
      38: { username: '', avatar: '', amount: 0, rank: 0 },
      39: { username: '', avatar: '', amount: 0, rank: 0 },
      40: { username: '', avatar: '', amount: 0, rank: 0 },
      41: { username: '', avatar: '', amount: 0, rank: 0 },
      42: { username: '', avatar: '', amount: 0, rank: 0 },
      43: { username: '', avatar: '', amount: 0, rank: 0 },
      44: { username: '', avatar: '', amount: 0, rank: 0 },
      45: { username: '', avatar: '', amount: 0, rank: 0 },
      46: { username: '', avatar: '', amount: 0, rank: 0 },
      47: { username: '', avatar: '', amount: 0, rank: 0 },
      48: { username: '', avatar: '', amount: 0, rank: 0 },
      49: { username: '', avatar: '', amount: 0, rank: 0 },
      50: { username: '', avatar: '', amount: 0, rank: 0 },
    },
  },
})

// Custom hook to access the rain data context
export const useLotteryData = () => useContext(LotteryDataContext)

// Provider component that wraps your AccountDataRetriever component
export const LotteryDataProvider = ({ children }) => {
  const socket = useSocket()
  const { account } = useWeb3React()
  const [lotteryData, setLotteryData] = useState({
    draw_active: false,
    settings: {
      enabled: true,
      stake_fee: 0.7,
      min_stakers: 10,
      winning_spots: 50,
      draw_timespan: 36000000,
    },
    lottery_data: {
      current_id: 0,
      total_kazama_burned: 0,
      current_pot: 0,
      next_draw: new Date(Date.now() + 3 * 60 * 60 * 1000),
      next_round_stakers: [],
      winners: {
        1: { username: '', avatar: '', amount: 0, rank: 0 },
        2: { username: '', avatar: '', amount: 0, rank: 0 },
        3: { username: '', avatar: '', amount: 0, rank: 0 },
        4: { username: '', avatar: '', amount: 0, rank: 0 },
        5: { username: '', avatar: '', amount: 0, rank: 0 },
        6: { username: '', avatar: '', amount: 0, rank: 0 },
        7: { username: '', avatar: '', amount: 0, rank: 0 },
        8: { username: '', avatar: '', amount: 0, rank: 0 },
        9: { username: '', avatar: '', amount: 0, rank: 0 },
        10: { username: '', avatar: '', amount: 0, rank: 0 },
        11: { username: '', avatar: '', amount: 0, rank: 0 },
        12: { username: '', avatar: '', amount: 0, rank: 0 },
        13: { username: '', avatar: '', amount: 0, rank: 0 },
        14: { username: '', avatar: '', amount: 0, rank: 0 },
        15: { username: '', avatar: '', amount: 0, rank: 0 },
        16: { username: '', avatar: '', amount: 0, rank: 0 },
        17: { username: '', avatar: '', amount: 0, rank: 0 },
        18: { username: '', avatar: '', amount: 0, rank: 0 },
        19: { username: '', avatar: '', amount: 0, rank: 0 },
        20: { username: '', avatar: '', amount: 0, rank: 0 },
        21: { username: '', avatar: '', amount: 0, rank: 0 },
        22: { username: '', avatar: '', amount: 0, rank: 0 },
        23: { username: '', avatar: '', amount: 0, rank: 0 },
        24: { username: '', avatar: '', amount: 0, rank: 0 },
        25: { username: '', avatar: '', amount: 0, rank: 0 },
        26: { username: '', avatar: '', amount: 0, rank: 0 },
        27: { username: '', avatar: '', amount: 0, rank: 0 },
        28: { username: '', avatar: '', amount: 0, rank: 0 },
        29: { username: '', avatar: '', amount: 0, rank: 0 },
        30: { username: '', avatar: '', amount: 0, rank: 0 },
        31: { username: '', avatar: '', amount: 0, rank: 0 },
        32: { username: '', avatar: '', amount: 0, rank: 0 },
        33: { username: '', avatar: '', amount: 0, rank: 0 },
        34: { username: '', avatar: '', amount: 0, rank: 0 },
        35: { username: '', avatar: '', amount: 0, rank: 0 },
        36: { username: '', avatar: '', amount: 0, rank: 0 },
        37: { username: '', avatar: '', amount: 0, rank: 0 },
        38: { username: '', avatar: '', amount: 0, rank: 0 },
        39: { username: '', avatar: '', amount: 0, rank: 0 },
        40: { username: '', avatar: '', amount: 0, rank: 0 },
        41: { username: '', avatar: '', amount: 0, rank: 0 },
        42: { username: '', avatar: '', amount: 0, rank: 0 },
        43: { username: '', avatar: '', amount: 0, rank: 0 },
        44: { username: '', avatar: '', amount: 0, rank: 0 },
        45: { username: '', avatar: '', amount: 0, rank: 0 },
        46: { username: '', avatar: '', amount: 0, rank: 0 },
        47: { username: '', avatar: '', amount: 0, rank: 0 },
        48: { username: '', avatar: '', amount: 0, rank: 0 },
        49: { username: '', avatar: '', amount: 0, rank: 0 },
        50: { username: '', avatar: '', amount: 0, rank: 0 },
      },
      previous_winners: {
        1: { username: '', avatar: '', amount: 0, rank: 0 },
        2: { username: '', avatar: '', amount: 0, rank: 0 },
        3: { username: '', avatar: '', amount: 0, rank: 0 },
        4: { username: '', avatar: '', amount: 0, rank: 0 },
        5: { username: '', avatar: '', amount: 0, rank: 0 },
        6: { username: '', avatar: '', amount: 0, rank: 0 },
        7: { username: '', avatar: '', amount: 0, rank: 0 },
        8: { username: '', avatar: '', amount: 0, rank: 0 },
        9: { username: '', avatar: '', amount: 0, rank: 0 },
        10: { username: '', avatar: '', amount: 0, rank: 0 },
        11: { username: '', avatar: '', amount: 0, rank: 0 },
        12: { username: '', avatar: '', amount: 0, rank: 0 },
        13: { username: '', avatar: '', amount: 0, rank: 0 },
        14: { username: '', avatar: '', amount: 0, rank: 0 },
        15: { username: '', avatar: '', amount: 0, rank: 0 },
        16: { username: '', avatar: '', amount: 0, rank: 0 },
        17: { username: '', avatar: '', amount: 0, rank: 0 },
        18: { username: '', avatar: '', amount: 0, rank: 0 },
        19: { username: '', avatar: '', amount: 0, rank: 0 },
        20: { username: '', avatar: '', amount: 0, rank: 0 },
        21: { username: '', avatar: '', amount: 0, rank: 0 },
        22: { username: '', avatar: '', amount: 0, rank: 0 },
        23: { username: '', avatar: '', amount: 0, rank: 0 },
        24: { username: '', avatar: '', amount: 0, rank: 0 },
        25: { username: '', avatar: '', amount: 0, rank: 0 },
        26: { username: '', avatar: '', amount: 0, rank: 0 },
        27: { username: '', avatar: '', amount: 0, rank: 0 },
        28: { username: '', avatar: '', amount: 0, rank: 0 },
        29: { username: '', avatar: '', amount: 0, rank: 0 },
        30: { username: '', avatar: '', amount: 0, rank: 0 },
        31: { username: '', avatar: '', amount: 0, rank: 0 },
        32: { username: '', avatar: '', amount: 0, rank: 0 },
        33: { username: '', avatar: '', amount: 0, rank: 0 },
        34: { username: '', avatar: '', amount: 0, rank: 0 },
        35: { username: '', avatar: '', amount: 0, rank: 0 },
        36: { username: '', avatar: '', amount: 0, rank: 0 },
        37: { username: '', avatar: '', amount: 0, rank: 0 },
        38: { username: '', avatar: '', amount: 0, rank: 0 },
        39: { username: '', avatar: '', amount: 0, rank: 0 },
        40: { username: '', avatar: '', amount: 0, rank: 0 },
        41: { username: '', avatar: '', amount: 0, rank: 0 },
        42: { username: '', avatar: '', amount: 0, rank: 0 },
        43: { username: '', avatar: '', amount: 0, rank: 0 },
        44: { username: '', avatar: '', amount: 0, rank: 0 },
        45: { username: '', avatar: '', amount: 0, rank: 0 },
        46: { username: '', avatar: '', amount: 0, rank: 0 },
        47: { username: '', avatar: '', amount: 0, rank: 0 },
        48: { username: '', avatar: '', amount: 0, rank: 0 },
        49: { username: '', avatar: '', amount: 0, rank: 0 },
        50: { username: '', avatar: '', amount: 0, rank: 0 },
      },
    },
  })

  // Fetch data
  const fetchData = async () => {
    try {
      const response = await axios.get(getLotteryData)
      setLotteryData(response.data.lottery_data)
      console.log(`New lottery data:`, response.data.lottery_data)
    } catch (error) {
      console.error('Error fetching lottery data:', error)
    }
  }

  // Execute retrieving
  useEffect(() => {
    fetchData()
  }, [])

  return <LotteryDataContext.Provider value={lotteryData}>{children}</LotteryDataContext.Provider>
}
